{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "('Processing Data', '/home/micah/temp/hzz4l_histos/histos2e2mu_25ns/output_DoubleEG_Run2016C-23Sep2016-v1_miniaod.root')\n",
      "('Processing Data', '/home/micah/temp/hzz4l_histos/histos2e2mu_25ns/output_DoubleEG_Run2016D-23Sep2016-v1_miniaod.root')\n",
      "('Processing Data', '/home/micah/temp/hzz4l_histos/histos2e2mu_25ns/output_DoubleEG_Run2016F-23Sep2016-v1_miniaod.root')\n",
      "('Processing Data', '/home/micah/temp/hzz4l_histos/histos2e2mu_25ns/output_DoubleMuon_Run2016B-23Sep2016-v3_miniaod_1.root')\n",
      "('Processing Data', '/home/micah/temp/hzz4l_histos/histos2e2mu_25ns/output_DoubleMuon_Run2016F-23Sep2016-v1_miniaod.root')\n",
      "('Processing GGH', '/home/micah/temp/hzz4l_histos/histos2e2mu_25ns/output_GluGluHToZZTo4L_M125_13TeV_powheg2_JHUgenV6_pythia8.root')\n",
      "('Processing HJJ', '/home/micah/temp/hzz4l_histos/histos2e2mu_25ns/output_GluGluHToZZTo4L_M125_13TeV_powheg2_minloHJJ_JHUgenV6_pythia8_afterHLT.root')\n",
      "('Processing ggZZ', '/home/micah/temp/hzz4l_histos/histos2e2mu_25ns/output_GluGluToContinToZZTo2e2mu_13TeV_MCFM701_pythia8.root')\n",
      "('Processing ggZZ', '/home/micah/temp/hzz4l_histos/histos2e2mu_25ns/output_GluGluToContinToZZTo2e2tau_13TeV_MCFM701_pythia8.root')\n",
      "('Processing ggZZ', '/home/micah/temp/hzz4l_histos/histos2e2mu_25ns/output_GluGluToContinToZZTo2mu2tau_13TeV_MCFM701_pythia8.root')\n",
      "('Processing Data', '/home/micah/temp/hzz4l_histos/histos2e2mu_25ns/output_MuonEG_Run2016B-23Sep2016-v3_miniaod_1.root')\n",
      "('Processing Data', '/home/micah/temp/hzz4l_histos/histos2e2mu_25ns/output_MuonEG_Run2016G-23Sep2016-v1_miniaod_2.root')\n",
      "('Processing ttH', '/home/micah/temp/hzz4l_histos/histos2e2mu_25ns/output_ttH_HToZZ_4LFilter_M125_13TeV_powheg2_JHUgenV6_pythia8.root')\n",
      "('Processing TTbar', '/home/micah/temp/hzz4l_histos/histos2e2mu_25ns/output_TTTo2L2Nu_noSC_TuneCUETP8M2T4_13TeV-powheg-pythia8.root')\n",
      "('Processing TTWJets', '/home/micah/temp/hzz4l_histos/histos2e2mu_25ns/output_TTWJetsToLNu_TuneCUETP8M1_13TeV-amcatnloFXFX-madspin-pythia8.root')\n",
      "('Processing TTZ', '/home/micah/temp/hzz4l_histos/histos2e2mu_25ns/output_TTZToLLNuNu_M-10_TuneCUETP8M1_13TeV-amcatnlo-pythia8.root')\n",
      "('Processing VBF', '/home/micah/temp/hzz4l_histos/histos2e2mu_25ns/output_VBF_HToZZTo4L_M125_13TeV_powheg2_JHUgenV6_pythia8.root')\n",
      "('Processing WH', '/home/micah/temp/hzz4l_histos/histos2e2mu_25ns/output_WminusH_HToZZTo4L_M125_13TeV_powheg2-minlo-HWJ_JHUgenV6_pythia8.root')\n",
      "('Processing WH', '/home/micah/temp/hzz4l_histos/histos2e2mu_25ns/output_WplusH_HToZZTo4L_M125_13TeV_powheg2-minlo-HWJ_JHUgenV6_pythia8.root')\n",
      "('Processing WWZ', '/home/micah/temp/hzz4l_histos/histos2e2mu_25ns/output_WWZ_TuneCUETP8M1_13TeV-amcatnlo-pythia8.root')\n",
      "('Processing WZ', '/home/micah/temp/hzz4l_histos/histos2e2mu_25ns/output_WZTo3LNu_TuneCUETP8M1_13TeV-powheg-pythia8.root')\n",
      "('Processing WZZ', '/home/micah/temp/hzz4l_histos/histos2e2mu_25ns/output_WZZ_TuneCUETP8M1_13TeV-amcatnlo-pythia8.root')\n",
      "('Processing ZH', '/home/micah/temp/hzz4l_histos/histos2e2mu_25ns/output_ZH_HToZZ_4LFilter_M125_13TeV_powheg2-minlo-HZJ_JHUgenV6_pythia8.root')\n",
      "('Processing qqZZ', '/home/micah/temp/hzz4l_histos/histos2e2mu_25ns/output_ZZTo4L_13TeV_powheg_pythia8.root')\n",
      "('Processing Data', '/home/micah/temp/hzz4l_histos/histos4e_25ns/output_DoubleEG_Run2016B-23Sep2016-v3_miniaod_1.root')\n",
      "('Processing Data', '/home/micah/temp/hzz4l_histos/histos4e_25ns/output_DoubleEG_Run2016C-23Sep2016-v1_miniaod.root')\n",
      "('Processing Data', '/home/micah/temp/hzz4l_histos/histos4e_25ns/output_DoubleEG_Run2016E-23Sep2016-v1_miniaod.root')\n",
      "('Processing GGH', '/home/micah/temp/hzz4l_histos/histos4e_25ns/output_GluGluHToZZTo4L_M125_13TeV_powheg2_JHUgenV6_pythia8.root')\n",
      "('Processing HJJ', '/home/micah/temp/hzz4l_histos/histos4e_25ns/output_GluGluHToZZTo4L_M125_13TeV_powheg2_minloHJJ_JHUgenV6_pythia8_afterHLT.root')\n",
      "('Processing ggZZ', '/home/micah/temp/hzz4l_histos/histos4e_25ns/output_GluGluToContinToZZTo2e2mu_13TeV_MCFM701_pythia8.root')\n",
      "('Processing ggZZ', '/home/micah/temp/hzz4l_histos/histos4e_25ns/output_GluGluToContinToZZTo2e2nu_13TeV_MCFM701_pythia8.root')\n",
      "('Processing ggZZ', '/home/micah/temp/hzz4l_histos/histos4e_25ns/output_GluGluToContinToZZTo2e2tau_13TeV_MCFM701_pythia8.root')\n",
      "('Processing ggZZ', '/home/micah/temp/hzz4l_histos/histos4e_25ns/output_GluGluToContinToZZTo4e_13TeV_MCFM701_pythia8.root')\n",
      "('Processing ggZZ', '/home/micah/temp/hzz4l_histos/histos4e_25ns/output_GluGluToContinToZZTo4tau_13TeV_MCFM701_pythia8.root')\n",
      "('Processing ttH', '/home/micah/temp/hzz4l_histos/histos4e_25ns/output_ttH_HToZZ_4LFilter_M125_13TeV_powheg2_JHUgenV6_pythia8.root')\n",
      "('Processing TTWJets', '/home/micah/temp/hzz4l_histos/histos4e_25ns/output_TTWJetsToLNu_TuneCUETP8M1_13TeV-amcatnloFXFX-madspin-pythia8.root')\n",
      "('Processing TTZ', '/home/micah/temp/hzz4l_histos/histos4e_25ns/output_TTZToLLNuNu_M-10_TuneCUETP8M1_13TeV-amcatnlo-pythia8.root')\n",
      "('Processing VBF', '/home/micah/temp/hzz4l_histos/histos4e_25ns/output_VBF_HToZZTo4L_M125_13TeV_powheg2_JHUgenV6_pythia8.root')\n",
      "('Processing WH', '/home/micah/temp/hzz4l_histos/histos4e_25ns/output_WminusH_HToZZTo4L_M125_13TeV_powheg2-minlo-HWJ_JHUgenV6_pythia8.root')\n",
      "('Processing WH', '/home/micah/temp/hzz4l_histos/histos4e_25ns/output_WplusH_HToZZTo4L_M125_13TeV_powheg2-minlo-HWJ_JHUgenV6_pythia8.root')\n",
      "('Processing WZZ', '/home/micah/temp/hzz4l_histos/histos4e_25ns/output_WZZ_TuneCUETP8M1_13TeV-amcatnlo-pythia8.root')\n",
      "('Processing ZH', '/home/micah/temp/hzz4l_histos/histos4e_25ns/output_ZH_HToZZ_4LFilter_M125_13TeV_powheg2-minlo-HZJ_JHUgenV6_pythia8.root')\n",
      "('Processing qqZZ', '/home/micah/temp/hzz4l_histos/histos4e_25ns/output_ZZTo4L_13TeV_powheg_pythia8.root')\n",
      "('Processing ZZZ', '/home/micah/temp/hzz4l_histos/histos4e_25ns/output_ZZZ_TuneCUETP8M1_13TeV-amcatnlo-pythia8.root')\n",
      "('Processing Data', '/home/micah/temp/hzz4l_histos/histos4mu_25ns/output_DoubleMuon_Run2016B-23Sep2016-v3_miniaod_1.root')\n",
      "('Processing Data', '/home/micah/temp/hzz4l_histos/histos4mu_25ns/output_DoubleMuon_Run2016F-23Sep2016-v1_miniaod.root')\n",
      "('Processing Data', '/home/micah/temp/hzz4l_histos/histos4mu_25ns/output_DoubleMuon_Run2016G-23Sep2016-v1_miniaod_2.root')\n",
      "('Processing Data', '/home/micah/temp/hzz4l_histos/histos4mu_25ns/output_DoubleMuon_Run2016H-PromptReco-v2_miniaod.root')\n",
      "('Processing GGH', '/home/micah/temp/hzz4l_histos/histos4mu_25ns/output_GluGluHToZZTo4L_M125_13TeV_powheg2_JHUgenV6_pythia8.root')\n",
      "('Processing HJJ', '/home/micah/temp/hzz4l_histos/histos4mu_25ns/output_GluGluHToZZTo4L_M125_13TeV_powheg2_minloHJJ_JHUgenV6_pythia8_afterHLT.root')\n",
      "('Processing ggZZ', '/home/micah/temp/hzz4l_histos/histos4mu_25ns/output_GluGluToContinToZZTo2mu2tau_13TeV_MCFM701_pythia8.root')\n",
      "('Processing ggZZ', '/home/micah/temp/hzz4l_histos/histos4mu_25ns/output_GluGluToContinToZZTo4mu_13TeV_MCFM701_pythia8.root')\n",
      "('Processing ttH', '/home/micah/temp/hzz4l_histos/histos4mu_25ns/output_ttH_HToZZ_4LFilter_M125_13TeV_powheg2_JHUgenV6_pythia8.root')\n",
      "('Processing TTWJets', '/home/micah/temp/hzz4l_histos/histos4mu_25ns/output_TTWJetsToLNu_TuneCUETP8M1_13TeV-amcatnloFXFX-madspin-pythia8.root')\n",
      "('Processing TTZ', '/home/micah/temp/hzz4l_histos/histos4mu_25ns/output_TTZToLLNuNu_M-10_TuneCUETP8M1_13TeV-amcatnlo-pythia8.root')\n",
      "('Processing VBF', '/home/micah/temp/hzz4l_histos/histos4mu_25ns/output_VBF_HToZZTo4L_M125_13TeV_powheg2_JHUgenV6_pythia8.root')\n",
      "('Processing WH', '/home/micah/temp/hzz4l_histos/histos4mu_25ns/output_WminusH_HToZZTo4L_M125_13TeV_powheg2-minlo-HWJ_JHUgenV6_pythia8.root')\n",
      "('Processing WH', '/home/micah/temp/hzz4l_histos/histos4mu_25ns/output_WplusH_HToZZTo4L_M125_13TeV_powheg2-minlo-HWJ_JHUgenV6_pythia8.root')\n",
      "('Processing ZH', '/home/micah/temp/hzz4l_histos/histos4mu_25ns/output_ZH_HToZZ_4LFilter_M125_13TeV_powheg2-minlo-HZJ_JHUgenV6_pythia8.root')\n",
      "('Processing qqZZ', '/home/micah/temp/hzz4l_histos/histos4mu_25ns/output_ZZTo4L_13TeV_powheg_pythia8.root')\n"
     ]
    }
   ],
   "source": [
    "import os\n",
    "import sys\n",
    "import cPickle as pickle\n",
    "from UserFunctions import formatInputs\n",
    "\n",
    "#loads input data\n",
    "path = '/home/micah/temp/hzz4l_histos/'\n",
    "file_names2e2mu = open(path+'histos2e2mu_25ns/file_names.txt','r')\n",
    "file_names4e = open(path+'histos4e_25ns/file_names.txt','r')\n",
    "file_names4mu = open(path+'histos4mu_25ns/file_names.txt','r')\n",
    "\n",
    "\n",
    "files_addresses = []\n",
    "for i in file_names2e2mu.readlines():\n",
    "    files_addresses.append( i.rstrip() )\n",
    "for i in file_names4e.readlines():\n",
    "    files_addresses.append( i.rstrip()  )\n",
    "for i in file_names4mu.readlines():\n",
    "    files_addresses.append( i.rstrip()  )\n",
    "\n",
    "#format inputs (Data & MC)\n",
    "comparison = '>='\n",
    "njets = 2\n",
    "min4lmass = 115\n",
    "max4lmass = 133\n",
    "events = formatInputs(files_addresses, comparison, njets, min4lmass, max4lmass)\n",
    "\n",
    "\n",
    "#clean outliers (components with few events)\n",
    "krm = []\n",
    "for ik in events:\n",
    "    nevents = len(events[ik])\n",
    "    sumw = 0\n",
    "    for i in range(nevents):\n",
    "        sumw += events[ik][i][2]\n",
    "    print '%s events: %i, normalized: %.4f' % (ik,nevents,sumw)\n",
    "    if(nevents < 10 or ik == 'GGH'):\n",
    "        krm.append(ik)\n",
    "        \n",
    "for ik in krm:\n",
    "    del events[ik]\n",
    "keys = []\n",
    "for ik in events:\n",
    "    keys.append(ik)\n",
    "print '----------- KEYS -----------'\n",
    "print keys    \n",
    "\n",
    "\n",
    "#save the dictionary\n",
    "fileout = open('hzz4l_{0}jets_m4l{1}-{2}GeV.pkl'.format(njets,min4lmass,max4lmass),'wb')\n",
    "pickle.dump( events, fileout )\n",
    "fileout.close()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "celltoolbar": "Raw Cell Format",
  "kernelspec": {
   "display_name": "Python 2",
   "language": "python",
   "name": "python2"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 2
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython2",
   "version": "2.7.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
